# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [28]:
df = pd.read_csv('weather_data.csv')
df = df.drop(columns=['Unnamed: 0'])
df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,east london,-33.0153,27.9116,53.85,63,0,7.34,ZA,1659314593
1,cidreira,-30.1811,-50.2056,58.66,89,3,9.53,BR,1659314615
2,vaini,-21.2000,-175.2000,80.76,89,75,6.91,TO,1659314616
3,jamestown,42.0970,-79.2353,74.84,72,20,4.61,US,1659314616
4,dingle,10.9995,122.6711,82.58,75,100,1.14,PH,1659314616
...,...,...,...,...,...,...,...,...,...
552,luderitz,-26.6481,15.1594,57.42,52,0,7.00,NaN,1659314877
553,north bend,43.4065,-124.2243,70.92,91,20,10.36,US,1659314878
554,misratah,32.3754,15.0925,81.63,75,0,10.49,LY,1659314878
555,stokmarknes,68.5646,14.9108,53.58,87,100,0.00,NO,1659314878
556,sechelt,49.4664,-123.7694,88.12,47,2,3.15,CA,1659314878

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [64]:
city_locations = df[['Lat', 'Lng']]
humidity = df['Humidity']

In [67]:
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(city_locations, weights=humidity, dissipating=False, max_intensity=100, point_radius=1)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [10]:
ideal_df = df.loc[(df['Max Temp'] < 85) & (df['Max Temp'] > 65)]
ideal_df = ideal_df.loc[ideal_df['Humidity'] < 60]
ideal_df = ideal_df.loc[ideal_df['Cloudiness'] < 75].reset_index(drop=True)
ideal_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,yellowknife,62.4560,-114.3525,68.52,40,40,9.22,CA,1659314616
1,balykshi,47.0667,51.8667,73.40,46,0,6.71,KZ,1659314770
2,mount isa,-20.7333,139.5000,76.77,23,0,6.91,AU,1659314772
3,kropotkin,45.4375,40.5756,73.26,52,0,9.10,RU,1659314773
4,talavera de la reina,39.9635,-4.8308,83.01,26,7,6.40,ES,1659314775
5,norman wells,65.2820,-126.8329,73.44,46,20,10.36,CA,1659314581
6,tortoli,39.9256,9.6572,78.62,53,0,8.05,IT,1659314623
7,asyut,27.1810,31.1837,84.38,41,17,8.77,EG,1659314615
8,guerrero negro,27.9769,-114.0611,79.03,55,18,14.03,MX,1659314795
9,granada,37.2500,-3.2500,74.30,32,0,5.17,ES,1659314579
10,nikolayevskaya,47.6139,41.5023,73.09,57,0,11.54,RU,1659314795
11,lata,40.1629,-8.3327,70.09,56,0,3.44,PT,1659314796
12,campina verde,-19.5356,-49.4864,71.04,36,0,2.91,BR,1659314801
13,turkistan,43.0000,68.0000,74.95,42,0,7.40,KZ,1659314802
14,bilibino,68.0546,166.4372,65.46,39,46,6.11,RU,1659314802
15,zarand,30.8127,56.5640,74.93,28,0,1.92,IR,1659314805
16,dusti,37.3481,68.6640,77.20,31,10,2.71,TJ,1659314805
17,olhao,37.0286,-7.8411,80.29,59,0,2.30,PT,1659314808
18,beyneu,45.3167,55.2000,79.63,41,6,8.59,KZ,1659314809
19,mata,40.6830,-7.4592,73.92,46,0,1.14,PT,1659314811
20,saint-ambroise,48.5501,-71.3324,76.60,50,60,8.05,CA,1659314813
21,jalu,29.0331,21.5482,82.02,48,0,15.23,LY,1659314814
22,la ronge,55.1001,-105.2842,71.82,49,40,9.22,CA,1659314570
23,tshikapa,-6.4167,20.8000,73.72,35,1,1.14,CD,1659314816
24,komsomolskiy,40.4272,71.7189,75.92,38,36,2.30,UZ,1659314816
25,sarab,38.6066,44.9883,73.62,52,50,0.69,IR,1659314817
26,tres lagoas,-20.7511,-51.6783,71.53,36,0,5.99,BR,1659314822
27,vale da amoreira,39.0697,-7.6985,73.72,47,0,4.18,PT,1659314826
28,pimenta bueno,-11.6725,-61.1936,76.23,39,0,0.43,BR,1659314828
29,port hedland,-20.3167,118.5667,71.65,43,37,6.91,AU,1659314835
30,aklavik,68.2191,-135.0107,67.21,44,68,4.00,CA,1659314836
31,romans-sur-isere,45.0464,5.0562,75.97,56,0,5.48,FR,1659314837
32,mahon,39.8885,4.2658,73.96,53,0,5.75,ES,1659314837
33,rio verde de mato grosso,-18.9181,-54.8442,74.97,33,0,3.60,BR,1659314838
34,korla,41.7597,86.1469,78.30,40,30,14.67,CN,1659314840
35,cascais,38.6979,-9.4215,76.35,58,0,8.01,PT,1659314844
36,wuda,39.4994,106.7117,80.37,57,19,19.77,CN,1659314846
37,shu,43.5983,73.7614,74.52,39,39,2.55,KZ,1659314850
38,takab,36.4009,47.1133,67.05,58,0,4.47,IR,1659314861
39,kuryk,43.2000,51.6500,79.43,41,0,6.87,KZ,1659314864
40,shubarshi,48.5872,57.1869,71.01,50,46,3.15,KZ,1659314865
41,aragarcas,-15.8975,-52.2508,72.21,29,0,0.69,BR,1659314877

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [13]:
hotel_df = ideal_df
hotel_df['Hotel Name'] = ""
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,yellowknife,62.4560,-114.3525,68.52,40,40,9.22,CA,1659314616,
1,balykshi,47.0667,51.8667,73.40,46,0,6.71,KZ,1659314770,
2,mount isa,-20.7333,139.5000,76.77,23,0,6.91,AU,1659314772,
3,kropotkin,45.4375,40.5756,73.26,52,0,9.10,RU,1659314773,
4,talavera de la reina,39.9635,-4.8308,83.01,26,7,6.40,ES,1659314775,
5,norman wells,65.2820,-126.8329,73.44,46,20,10.36,CA,1659314581,
6,tortoli,39.9256,9.6572,78.62,53,0,8.05,IT,1659314623,
7,asyut,27.1810,31.1837,84.38,41,17,8.77,EG,1659314615,
8,guerrero negro,27.9769,-114.0611,79.03,55,18,14.03,MX,1659314795,
9,granada,37.2500,-3.2500,74.30,32,0,5.17,ES,1659314579,
10,nikolayevskaya,47.6139,41.5023,73.09,57,0,11.54,RU,1659314795,
11,lata,40.1629,-8.3327,70.09,56,0,3.44,PT,1659314796,
12,campina verde,-19.5356,-49.4864,71.04,36,0,2.91,BR,1659314801,
13,turkistan,43.0000,68.0000,74.95,42,0,7.40,KZ,1659314802,
14,bilibino,68.0546,166.4372,65.46,39,46,6.11,RU,1659314802,
15,zarand,30.8127,56.5640,74.93,28,0,1.92,IR,1659314805,
16,dusti,37.3481,68.6640,77.20,31,10,2.71,TJ,1659314805,
17,olhao,37.0286,-7.8411,80.29,59,0,2.30,PT,1659314808,
18,beyneu,45.3167,55.2000,79.63,41,6,8.59,KZ,1659314809,
19,mata,40.6830,-7.4592,73.92,46,0,1.14,PT,1659314811,
20,saint-ambroise,48.5501,-71.3324,76.60,50,60,8.05,CA,1659314813,
21,jalu,29.0331,21.5482,82.02,48,0,15.23,LY,1659314814,
22,la ronge,55.1001,-105.2842,71.82,49,40,9.22,CA,1659314570,
23,tshikapa,-6.4167,20.8000,73.72,35,1,1.14,CD,1659314816,
24,komsomolskiy,40.4272,71.7189,75.92,38,36,2.30,UZ,1659314816,
25,sarab,38.6066,44.9883,73.62,52,50,0.69,IR,1659314817,
26,tres lagoas,-20.7511,-51.6783,71.53,36,0,5.99,BR,1659314822,
27,vale da amoreira,39.0697,-7.6985,73.72,47,0,4.18,PT,1659314826,
28,pimenta bueno,-11.6725,-61.1936,76.23,39,0,0.43,BR,1659314828,
29,port hedland,-20.3167,118.5667,71.65,43,37,6.91,AU,1659314835,
30,aklavik,68.2191,-135.0107,67.21,44,68,4.00,CA,1659314836,
31,romans-sur-isere,45.0464,5.0562,75.97,56,0,5.48,FR,1659314837,
32,mahon,39.8885,4.2658,73.96,53,0,5.75,ES,1659314837,
33,rio verde de mato grosso,-18.9181,-54.8442,74.97,33,0,3.60,BR,1659314838,
34,korla,41.7597,86.1469,78.30,40,30,14.67,CN,1659314840,
35,cascais,38.6979,-9.4215,76.35,58,0,8.01,PT,1659314844,
36,wuda,39.4994,106.7117,80.37,57,19,19.77,CN,1659314846,
37,shu,43.5983,73.7614,74.52,39,39,2.55,KZ,1659314850,
38,takab,36.4009,47.1133,67.05,58,0,4.47,IR,1659314861,
39,kuryk,43.2000,51.6500,79.43,41,0,6.87,KZ,1659314864,
40,shubarshi,48.5872,57.1869,71.01,50,46,3.15,KZ,1659314865,
41,aragarcas,-15.8975,-52.2508,72.21,29,0,0.69,BR,1659314877,

In [15]:
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
}
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
hotel_address = requests.get(base_url, params=params)
hotel_json = hotel_address.json()

In [26]:
hotel_json
test = hotel_json['results'][0]['geometry']['location']
test_lat = test['lat']
test_lng = test['lng']
hotel_json['results'][0]['name']

'The Explorer Hotel'

In [37]:
for index, row in hotel_df.iterrows():
    params['location'] = f'{row["Lat"]},{row["Lng"]}'
    hotel_address = requests.get(base_url, params=params)
    hotel_json = hotel_address.json()
    try:
        hotel_df.loc[index, 'Hotel Name'] = hotel_json['results'][0]['name']
    except (KeyError, IndexError):
        hotel_df.loc[index, 'Hotel Name'] = 'N/A'

In [50]:
hotel_names = hotel_df['Hotel Name'].tolist()
city_list = hotel_df['City'].tolist()
country_list = hotel_df['Country'].tolist()
print(len(hotel_names))
print(len(city_list))
print(len(country_list))

42
42
42

In [82]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [85]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(marker_locations, info_box_content=hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))